### PR TITLE
Async GraphQL View

### PR DESCRIPTION
**Pull request by dorianamouroux**
# Description

PR following the discussion from here: https://github.com/reset-button/ariadne_django/issues/20

I created a new `GraphQLAsyncView` which leverage the async capabilities of Django:

- Refactor the GraphQL View to be in two parts: The BaseView and the GraphQL View. I replaced `execute_query` with `get_kwargs_graphql`. The `post` method can call `graphql_sync` directly.

- Define a GraphQLAsyncView which will be async and call the async graphql from Ariadne. I had to duplicate some code from the sync version, because Django doesn't have an official `raise Http400`

- The Dispatch method checks for the schema instead of the post method. It simplifies the `post` method while also making sure you don't have a playground without schema neither.

- Write specs for GraphQLAsyncView, mainly duplicating the tests we have now but using async. Maybe there is a way to have tests written once, and they test both the async and sync version? But for now duplication if fine I think.

I followed the article https://medium.com/@bruno.fosados/django-async-class-based-views-acbv-5986c4511ae6 to write the view async by using:

```python
    @classonlymethod
    def as_view(cls, **initkwargs):
        view = super().as_view(**initkwargs)
        view._is_coroutine = asyncio.coroutines._is_coroutine
        return view
```

Which I also define `csrf_exempt=True` in it, as the decorator doesn't work in async yet.

### CODE REVIEW

**Comment by dorianamouroux** [comment]
Checks aren't run, any idea why?

**Comment by kedlav** [comment]
> Checks aren't run, any idea why?

I'm checking on this right now.  Thanks for the heads up (and the PR!)

**Comment by kedlav** [comment]
> Checks aren't run, any idea why?

I have no idea why this was required here but not on the core ariadne project, but this should work for all subsequent pull requests.  I updated the workflow to handle pull request events as well, then created a new test github user that is not in my organization and filed a test pull request.  It looks like actions ran and all is working now:

https://github.com/reset-button/ariadne_django/pull/24

As I am unsure how to force the repo to run tests on your branch, we can either close and reopen this one, or I can create a new PR.  Totally up to you.  I'll be reviewing this code tonight/tomorrow night.

**Comment by dorianamouroux** [comment]
> > Checks aren't run, any idea why?
> 
> I have no idea why this was required here but not on the core ariadne project, but this should work for all subsequent pull requests. I updated the workflow to handle pull request events as well, then created a new test github user that is not in my organization and filed a test pull request. It looks like actions ran and all is working now:
> 
> #24
> 
> As I am unsure how to force the repo to run tests on your branch, we can either close and reopen this one, or I can create a new PR. Totally up to you. I'll be reviewing this code tonight/tomorrow night.

Close/reopen could trigger the checks, all good! Thanks!

**Comment by markedwards** [comment]
I've had a chance to review and test this.  It's largely similar to the implementation I did locally.

I notice a few things:

1. I get `object HttpResponse can't be used in 'await' expression` when loading the GraphQL Playground.  This is because `GraphQLAsyncView.get()` needs to be async.  To minimize duplication, I suggest defining `BaseView._get()` and then implementing the sync and async `get()` variants in `GraphQLView` and `GraphAsyncQLView`.
1a. Related to the above, there is a perhaps nitpicky mypy error when defining `get()` as async on `GraphAsyncQLView` that the signature doesn't match the superclass.  If you want to appease that, I did `class BaseView(TemplateResponseMixin, ContextMixin, View)` and that seems to work well.  That said, there are mypy errors aplenty in the code if you run strict, and I'm not sure there is any serious danger in the signature conflict.
2. I believe you can actually use `@method_decorator(csrf_exempt, name="dispatch")` on `GraphAsyncQLView` now that `GraphAsyncQLView.__call__()` is sync.  Not sure this is necessarily preferable, just noting it.
3. Nitpick -- maybe rename `BaseView` to `BaseGraphQLView` or `GraphQLBaseView` so its less generic?

**Comment by dorianamouroux** [comment]
> I've had a chance to review and test this. It's largely similar to the implementation I did locally.
> 
> I notice a few things:
> 
> 1. I get `object HttpResponse can't be used in 'await' expression` when loading the GraphQL Playground.  This is because `GraphQLAsyncView.get()` needs to be async.  To minimize duplication, I suggest defining `BaseView._get()` and then implementing the sync and async `get()` variants in `GraphQLView` and `GraphAsyncQLView`.
> 2. Related to the above, there is a mypy error when defining `get()` as async on `GraphAsyncQLView` that the signature doesn't match the superclass.  If you want to appease that, I did `class BaseView(TemplateResponseMixin, ContextMixin, View)` and that seems to work well.  That said, there are mypy errors aplenty in the code if you run strict, and I'm not sure there is any serious danger in the signature conflict.
> 3. I believe you can actually use `@method_decorator(csrf_exempt, name="dispatch")` on `GraphAsyncQLView` now that `GraphAsyncQLView.__call__()` is sync.  Not sure this is necessarily preferable, just noting it.
> 4. Nitpick -- maybe rename `BaseView` to `BaseGraphQLView` or `GraphQLBaseView` so its less generic?

Thanks a lot for the thorough review! I addressed all of your comments. I'm quite surprised about the 1st one, I would except the Django construct to take care of awaiting coroutines.

Let me know if there is something else that could be improved

**Comment by markedwards** [comment]
Looks good to me!

**Review by maxmorlocke — CHANGES_REQUESTED** [review]
Code looks great.  Can we split into individual files similar to scalars, etc. and import them in __init__.py to match the code style of the rest of the project?

Thanks @dorianamouroux for the code and @markedwards for the feedback.  It's really great to see people so eager to contribute!!  Happy to cut a 0.2 release with this as soon as we get it merged.

**Comment by dorianamouroux** [comment]
> Code looks great. Can we split into individual files similar to scalars, etc. and import them in **init**.py to match the code style of the rest of the project?
> 
> Thanks @dorianamouroux for the code and @markedwards for the feedback. It's really great to see people so eager to contribute!! Happy to cut a 0.2 release with this as soon as we get it merged.

I created one file for async view; one for sync and one for the base, let me know if that's good enough. When ReadTheDocs is up and running, happy to write a little thing for async view

**Review by maxmorlocke — APPROVED** [review]

**Comment by maxmorlocke** [comment]
Thanks @dorianamouroux!  I've merged things up.  Hopeful to cut the 0.2.0 release in the next couple of days.

**Comment by jokerol** [comment]
This feature saved me.. really. ( from 'RuntimeWarning: coroutine 'xxx' was never awaited' )
And Hope it introduce in Readme text.
Readme shows only using GraphQLView not GraphQLAsyncView..
Beginners may have hard time to figure it out.. using async resolver should use GraphQLAsyncView..

**Pull request merged**
